sudo: false
language: python
env:
  - TOXENV=py27-dj15
  - TOXENV=py27-dj16
  - TOXENV=py27-dj17
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py33-dj15
  - TOXENV=py33-dj16
  - TOXENV=py33-dj17
  - TOXENV=py33-dj18
  - TOXENV=py34-dj17
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=coverage
install:
  - pip install tox
  - if [ "$TOXENV" = "coverage" ]; then pip install coveralls; fi
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - tox
after_success:
  - if [ "$TOXENV" = "coverage" ]; then coveralls; fi
